//! First-run AppData profile for the click-run solo product (no user config.yaml).

use crate::app_dirs::{
    default_inprocess_kaspad_appdir, default_inprocess_zkas_kaspad_appdir,
    default_runtime_config_path, get_bridge_app_dir, get_bridge_logs_dir,
};
use std::io::{self, Write};
use std::net::UdpSocket;
use std::path::PathBuf;

/// Default Stratum port ASICs connect to (not :6666 dual-external / hosted solo).
pub const PRODUCT_STRATUM_PORT: u16 = 7666;

/// Default local dashboard port (not :3130 dual-external).
pub const PRODUCT_DASHBOARD_PORT: u16 = 3133;

/// Per-instance Prometheus scrape port (not :2166 dual-external).
pub const PRODUCT_PROM_PORT: u16 = 3266;

/// Embedded runtime YAML — fee is NOT listed (hardcoded in binary).
const RUNTIME_YAML: &str = r#"# Auto-generated by RKstratumKasZkasSolo — do not put fee wallets here.
# Hosting fee is permanently locked at 1% inside the binary.

kaspad_address: "127.0.0.1:16110"
block_wait_time: 1000
print_stats: true
log_to_file: true
health_check_port: ""
web_dashboard_port: ":3133"
var_diff: true
shares_per_min: 20
var_diff_stats: true
pow2_clamp: true
extranonce_size: 2
coinbase_tag_suffix: "rksolo"
nicehash_min_share_diff: 16384
approximate_geo_lookup: false

zkas_merged:
  enabled: true
  dry_run: false
  zkas_rpc: "127.0.0.1:16810"
  zkas_p2p: "127.0.0.1:16811"
  zkas_appdir: ""
  wallet_api: ""
  fallback_zkas_address: ""
  pending_cap: 64
  consolidate_enabled: false
  consolidate_note_threshold: 40
  consolidate_interval_ms: 600000
  consolidate_fee_sompi: 10000000
  max_spends_per_tx: 20
  seed_path: ""
  consolidate_address: ""

mps_crawler:
  enabled: false
  pool_name: "RKstratum Kas+ZKAS Solo"
  website: ""
  stratum_url: ""

instances:
  - stratum_port: ":7666"
    min_share_diff: 64
    prom_port: ":3266"
    log_to_file: true
"#;

fn runtime_needs_port_refresh(content: &str) -> bool {
    content.contains("stratum_port: \":6666\"")
        || content.contains("web_dashboard_port: \":3130\"")
        || content.contains("prom_port: \":2166\"")
        || !content.contains("stratum_port: \":7666\"")
        || !content.contains("web_dashboard_port: \":3133\"")
}

/// Ensure AppData dirs + runtime.yaml exist; return path to use as `--config`.
pub fn ensure_product_runtime() -> Result<PathBuf, anyhow::Error> {
    let app = get_bridge_app_dir();
    std::fs::create_dir_all(&app)?;
    std::fs::create_dir_all(get_bridge_logs_dir())?;
    std::fs::create_dir_all(default_inprocess_kaspad_appdir())?;
    std::fs::create_dir_all(default_inprocess_zkas_kaspad_appdir())?;

    let cfg = default_runtime_config_path();
    let rewrite = if cfg.exists() {
        let existing = std::fs::read_to_string(&cfg).unwrap_or_default();
        runtime_needs_port_refresh(&existing)
    } else {
        true
    };
    if rewrite {
        std::fs::write(&cfg, RUNTIME_YAML)?;
        eprintln!(
            "Wrote runtime profile (stratum :{PRODUCT_STRATUM_PORT}, dashboard :{PRODUCT_DASHBOARD_PORT}, prom :{PRODUCT_PROM_PORT}):\n  {}\n  Kaspa data: {}\n  ZKAS data:  {}",
            cfg.display(),
            default_inprocess_kaspad_appdir().display(),
            default_inprocess_zkas_kaspad_appdir().display()
        );
    }
    Ok(cfg)
}

/// Best-effort LAN IPv4 for ASIC instructions (not 127.0.0.1).
pub fn guess_lan_ipv4() -> Option<String> {
    let socket = UdpSocket::bind("0.0.0.0:0").ok()?;
    socket.connect("8.8.8.8:80").ok()?;
    let ip = socket.local_addr().ok()?.ip();
    match ip {
        std::net::IpAddr::V4(v4) if !v4.is_loopback() => Some(v4.to_string()),
        _ => None,
    }
}

pub fn print_startup_banner() {
    let lan = guess_lan_ipv4().unwrap_or_else(|| "YOUR-PC-LAN-IP".to_string());
    eprintln!("==============================================");
    eprintln!("  RKstratum Kas + ZKAS Solo (click-run)");
    eprintln!("  Hosting fee: permanently 1% (hardcoded)");
    eprintln!("==============================================");
    eprintln!("  First sync of Kaspa + ZKAS can take a long time");
    eprintln!("  and needs substantial SSD space.");
    eprintln!();
    eprintln!("  When sync finishes, point your ASIC at:");
    eprintln!("    stratum+tcp://{lan}:{PRODUCT_STRATUM_PORT}");
    eprintln!("  Dashboard (local): http://127.0.0.1:{PRODUCT_DASHBOARD_PORT}/");
    eprintln!("  Allow inbound TCP {PRODUCT_STRATUM_PORT} in Windows Firewall if needed.");
    eprintln!("==============================================");
    let _ = io::stderr().flush();
}

pub fn print_ready_banner() {
    let lan = guess_lan_ipv4().unwrap_or_else(|| "YOUR-PC-LAN-IP".to_string());
    tracing::info!("==============================================");
    tracing::info!("  NODES READY — Stratum listening");
    tracing::info!("  ASIC → stratum+tcp://{lan}:{PRODUCT_STRATUM_PORT}");
    tracing::info!("  Dashboard → http://127.0.0.1:{PRODUCT_DASHBOARD_PORT}/");
    tracing::info!("  Fee lock → 1% ops wallets (cannot be changed)");
    tracing::info!("==============================================");
}

/// Keep a double-clicked Windows console open after a fatal error.
pub fn hold_console_on_error() {
    #[cfg(windows)]
    {
        eprint!("\nPress Enter to exit...");
        let _ = io::stderr().flush();
        let mut line = String::new();
        let _ = io::stdin().read_line(&mut line);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn runtime_yaml_uses_product_ports() {
        assert!(RUNTIME_YAML.contains("stratum_port: \":7666\""));
        assert!(RUNTIME_YAML.contains("web_dashboard_port: \":3133\""));
        assert!(RUNTIME_YAML.contains("prom_port: \":3266\""));
        assert!(!RUNTIME_YAML.contains("stratum_port: \":6666\""));
        assert!(!RUNTIME_YAML.contains("web_dashboard_port: \":3130\""));
        assert!(!runtime_needs_port_refresh(RUNTIME_YAML));
        assert!(runtime_needs_port_refresh(
            "web_dashboard_port: \":3130\"\ninstances:\n  - stratum_port: \":6666\"\n    prom_port: \":2166\"\n"
        ));
    }

    #[test]
    fn product_port_constants() {
        assert_eq!(PRODUCT_STRATUM_PORT, 7666);
        assert_eq!(PRODUCT_DASHBOARD_PORT, 3133);
        assert_eq!(PRODUCT_PROM_PORT, 3266);
    }
}
